<#
.SYNOPSIS
    Writes a minimal AcroForm PDF used to test form filling.

.DESCRIPTION
    There was no PDF with form fields anywhere on the development machine, and
    a downloaded sample would be an undocumented binary blob in the repo. This
    generates the fixture instead: the source is readable, the output is
    deterministic, and what it contains is exactly what the test needs --
    two text fields, a checkbox, and nothing else.

    A PDF is a byte-offset-indexed format, so the cross-reference table has to
    record where each object starts. That is why this builds the file object by
    object while tracking offsets rather than just concatenating strings.

.EXAMPLE
    ./scripts/make-form-fixture.ps1
#>

[CmdletBinding()]
param(
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot "tests\fixtures\form-simple.pdf"
}
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null

# Latin-1 keeps one byte per character, so string length equals byte offset.
$enc = [System.Text.Encoding]::GetEncoding(28591)

$objects = [System.Collections.Generic.List[string]]::new()

function Add-Object([string]$body) {
    $script:objects.Add($body)
    return $script:objects.Count   # 1-based object number
}

# 1: Catalog -- references the AcroForm dictionary, which is what makes a
#    viewer treat the widgets as fillable rather than as flat annotations.
$catalog = @"
<< /Type /Catalog /Pages 2 0 R
   /AcroForm << /Fields [5 0 R 6 0 R 7 0 R] /DA (/Helv 0 Tf 0 g) /DR << /Font << /Helv 4 0 R >> >> >>
>>
"@
Add-Object $catalog | Out-Null

# 2: Page tree
Add-Object "<< /Type /Pages /Kids [3 0 R] /Count 1 >>" | Out-Null

# 3: The page. Widget annotations are listed in /Annots like any annotation.
$page = @"
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]
   /Resources << /Font << /Helv 4 0 R >> >>
   /Contents 8 0 R
   /Annots [5 0 R 6 0 R 7 0 R]
>>
"@
Add-Object $page | Out-Null

# 4: Helvetica, one of the 14 standard fonts, so nothing has to be embedded.
Add-Object "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>" | Out-Null

# 5, 6: text fields. /FT /Tx with /Ff 0 is a plain single-line text field.
$fieldName = @"
<< /Type /Annot /Subtype /Widget /FT /Tx /T (name) /TU (Full name)
   /Rect [160 660 460 686] /F 4 /DA (/Helv 12 Tf 0 g) /V ()
   /MK << /BC [0.6 0.6 0.6] /BG [1 1 1] >> /Border [0 0 1]
>>
"@
Add-Object $fieldName | Out-Null

$fieldEmail = @"
<< /Type /Annot /Subtype /Widget /FT /Tx /T (email) /TU (Email address)
   /Rect [160 610 460 636] /F 4 /DA (/Helv 12 Tf 0 g) /V ()
   /MK << /BC [0.6 0.6 0.6] /BG [1 1 1] >> /Border [0 0 1]
>>
"@
Add-Object $fieldEmail | Out-Null

# 7: checkbox. /AS /Off selects which appearance state is currently shown.
$fieldAgree = @"
<< /Type /Annot /Subtype /Widget /FT /Btn /T (agree) /TU (I agree)
   /Rect [160 560 178 578] /F 4 /V /Off /AS /Off
   /MK << /BC [0.4 0.4 0.4] /BG [1 1 1] /CA (4) >> /Border [0 0 1]
>>
"@
Add-Object $fieldAgree | Out-Null

# 8: page content -- the labels beside each field.
$contentText = @"
BT /Helv 18 Tf 72 720 Td (LumenPDF form fixture) Tj ET
BT /Helv 12 Tf 72 666 Td (Full name:) Tj ET
BT /Helv 12 Tf 72 616 Td (Email:) Tj ET
BT /Helv 12 Tf 190 565 Td (I agree to the terms) Tj ET
BT /Helv 9 Tf 72 520 Td (Generated by scripts/make-form-fixture.ps1) Tj ET
"@
$contentStream = "<< /Length $($enc.GetByteCount($contentText)) >>`nstream`n$contentText`nendstream"
Add-Object $contentStream | Out-Null

# -- Assemble, tracking byte offsets for the xref table ---------------------
$sb = [System.Text.StringBuilder]::new()

# %PDF-1.7 then a binary comment, which marks the file as containing binary
# data so naive tools do not mangle it on transfer.
[void]$sb.Append("%PDF-1.7`n")
[void]$sb.Append("%" + [char]0xE2 + [char]0xE3 + [char]0xCF + [char]0xD3 + "`n")

$offsets = @()
for ($i = 0; $i -lt $objects.Count; $i++) {
    $offsets += $sb.Length
    [void]$sb.Append("$($i + 1) 0 obj`n")
    [void]$sb.Append($objects[$i].TrimEnd())
    [void]$sb.Append("`nendobj`n")
}

$xrefOffset = $sb.Length

# Entry format is fixed-width: 10-digit offset, 5-digit generation, type.
[void]$sb.Append("xref`n0 $($objects.Count + 1)`n")
[void]$sb.Append("0000000000 65535 f `n")
foreach ($offset in $offsets) {
    [void]$sb.Append(("{0:D10} 00000 n `n" -f $offset))
}

[void]$sb.Append("trailer`n<< /Size $($objects.Count + 1) /Root 1 0 R >>`n")
[void]$sb.Append("startxref`n$xrefOffset`n%%EOF`n")

[System.IO.File]::WriteAllBytes($OutputPath, $enc.GetBytes($sb.ToString()))

Write-Host "Wrote $OutputPath ($((Get-Item $OutputPath).Length) bytes)" -ForegroundColor Green
Write-Host "Fields: name (text), email (text), agree (checkbox)"
