<#
.SYNOPSIS
    Writes a two-page PDF containing link annotations.

.DESCRIPTION
    Covers the three cases the viewer has to tell apart:

      * an internal GoTo link, which must navigate without leaving the app
      * an external URI link, which must be confirmed before anything opens
      * a Launch action, which must be recognised and refused -- a document
        should not be able to start a program by being clicked

    It also includes a link whose visible text disagrees with its target, which
    is the case the URI preview exists for.

.EXAMPLE
    ./scripts/make-link-fixture.ps1
#>

[CmdletBinding()]
param(
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot "tests\fixtures\links.pdf"
}
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null

$enc = [System.Text.Encoding]::GetEncoding(28591)
$objects = [System.Collections.Generic.List[string]]::new()

function Add-Object([string]$body) {
    $script:objects.Add($body)
    return $script:objects.Count
}

# 1: Catalog
Add-Object "<< /Type /Catalog /Pages 2 0 R >>" | Out-Null

# 2: Page tree
Add-Object "<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>" | Out-Null

# 3: page 1, carrying every link
$page1 = @"
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]
   /Resources << /Font << /Helv 5 0 R >> >>
   /Contents 6 0 R
   /Annots [8 0 R 9 0 R 10 0 R 11 0 R]
>>
"@
Add-Object $page1 | Out-Null

# 4: page 2, the destination of the internal link
$page2 = @"
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]
   /Resources << /Font << /Helv 5 0 R >> >>
   /Contents 7 0 R
>>
"@
Add-Object $page2 | Out-Null

# 5: Helvetica
Add-Object "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>" | Out-Null

# 6: page 1 content
$content1 = @"
BT /Helv 18 Tf 72 720 Td (LumenPDF link fixture) Tj ET
BT /Helv 12 Tf 72 680 Td (Go to page two) Tj ET
BT /Helv 12 Tf 72 640 Td (Visit example.com) Tj ET
BT /Helv 12 Tf 72 600 Td (https://example.com/safe) Tj ET
BT /Helv 12 Tf 72 560 Td (Open a program) Tj ET
BT /Helv 9 Tf 72 520 Td (Generated by scripts/make-link-fixture.ps1) Tj ET
"@
$stream1 = "<< /Length $($enc.GetByteCount($content1)) >>`nstream`n$content1`nendstream"
Add-Object $stream1 | Out-Null

# 7: page 2 content
$content2 = @"
BT /Helv 18 Tf 72 720 Td (Page two) Tj ET
BT /Helv 12 Tf 72 680 Td (The internal link lands here.) Tj ET
"@
$stream2 = "<< /Length $($enc.GetByteCount($content2)) >>`nstream`n$content2`nendstream"
Add-Object $stream2 | Out-Null

# 8: internal GoTo. /Border [0 0 0] keeps PDF viewers from drawing a box --
#    the affordance is the cursor, not a rectangle printed on the page.
$linkGoto = @"
<< /Type /Annot /Subtype /Link /Rect [72 674 200 692] /Border [0 0 0]
   /Dest [4 0 R /XYZ 0 792 0] >>
"@
Add-Object $linkGoto | Out-Null

# 9: external URI
$linkUri = @"
<< /Type /Annot /Subtype /Link /Rect [72 634 200 652] /Border [0 0 0]
   /A << /Type /Action /S /URI /URI (https://example.com/) >> >>
"@
Add-Object $linkUri | Out-Null

# 10: the label says example.com, the target does not. This is why the app
#     shows the URI and asks, instead of trusting what is printed on the page.
$linkMismatch = @"
<< /Type /Annot /Subtype /Link /Rect [72 594 260 612] /Border [0 0 0]
   /A << /Type /Action /S /URI /URI (https://not-example.invalid/elsewhere) >> >>
"@
Add-Object $linkMismatch | Out-Null

# 11: Launch. Must be reported as unsupported rather than followed.
$linkLaunch = @"
<< /Type /Annot /Subtype /Link /Rect [72 554 200 572] /Border [0 0 0]
   /A << /Type /Action /S /Launch /F (cmd.exe) >> >>
"@
Add-Object $linkLaunch | Out-Null

# -- Assemble ---------------------------------------------------------------
$sb = [System.Text.StringBuilder]::new()
[void]$sb.Append("%PDF-1.7`n")
[void]$sb.Append("%" + [char]0xE2 + [char]0xE3 + [char]0xCF + [char]0xD3 + "`n")

$offsets = @()
for ($i = 0; $i -lt $objects.Count; $i++) {
    $offsets += $sb.Length
    [void]$sb.Append("$($i + 1) 0 obj`n")
    [void]$sb.Append($objects[$i].TrimEnd())
    [void]$sb.Append("`nendobj`n")
}

$xrefOffset = $sb.Length
[void]$sb.Append("xref`n0 $($objects.Count + 1)`n")
[void]$sb.Append("0000000000 65535 f `n")
foreach ($offset in $offsets) {
    [void]$sb.Append(("{0:D10} 00000 n `n" -f $offset))
}

[void]$sb.Append("trailer`n<< /Size $($objects.Count + 1) /Root 1 0 R >>`n")
[void]$sb.Append("startxref`n$xrefOffset`n%%EOF`n")

[System.IO.File]::WriteAllBytes($OutputPath, $enc.GetBytes($sb.ToString()))

Write-Host "Wrote $OutputPath ($((Get-Item $OutputPath).Length) bytes)" -ForegroundColor Green
Write-Host "Page 1 links: GoTo page 2, URI, URI with a misleading label, Launch (must be refused)"
